/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef __CCE_RUNTIME_STARS_BASE_HPP__
#define __CCE_RUNTIME_STARS_BASE_HPP__

#include <cstdint>
#include "base.h"

namespace cce {
namespace runtime {

constexpr uint32_t SQE_BIZ_FLAG_DATADUMP = 0x1U;
constexpr uint32_t SQE_BIZ_FLAG_BIUPERF = 0x2U;
constexpr uint32_t SQE_BIZ_FLAG_L2CACHE = 0x4U;
constexpr uint8_t SQE_DCACHE_LOCK_FLAG = 0x8U;
constexpr uint32_t SQE_NUM_PER_STARS_TASK_MAX = 4U;
constexpr uint32_t SQE_NUM_PER_DAVID_TASK_MAX = 5U;
constexpr uint64_t TS_STARS_COND_DFX_SIZE = 128ULL;
constexpr uint32_t TS_STARS_ERROR_MAX_INDEX = 6U;

// command field defines for dvpp(vpc, jpege, jpegd)
constexpr uint32_t STARS_DVPP_SQE_CMDLIST_ADDR_LOW_IDX = 12U;
constexpr uint32_t STARS_DVPP_SQE_CMDLIST_ADDR_HIGH_IDX = 13U;

constexpr uint8_t RT_STARS_DEFAULT_KERNEL_CREDIT = 254U;
constexpr uint8_t RT_STARS_DEFAULT_KERNEL_CREDIT_DAVID = 253U;
constexpr uint8_t RT_STARS_DEFAULT_AICPU_KERNEL_CREDIT_MIN = 8U;
constexpr uint8_t RT_STARS_DEFAULT_AICPU_KERNEL_CREDIT_MAX = 16U;
constexpr uint8_t RT_STARS_ADJUST_KERNEL_CREDIT = 254U;
constexpr uint8_t RT_STARS_MAX_KERNEL_CREDIT = 254U;
constexpr uint8_t RT_STARS_NEVER_TIMEOUT_KERNEL_CREDIT = 255U;
constexpr uint8_t RT_STARS_EXIST_ERROR = 0x3FU;
constexpr uint8_t RT_STARS_EXIST_WARNING = 0x40U;
constexpr uint16_t RT_SYNC_TASK_FLAG = 0x8000U;
constexpr uint64_t RT_GET_HEAD_CYCLE_NUM = 100000000U;
constexpr uint64_t RT_QUERY_CNT_NUM = 200000U;
constexpr uint8_t RT_STARS_AICPU_MODEL_KERNEL_CREDIT = 18U;
constexpr uint8_t RT_STARS_AICPU_DEFAULT_TIMEOUT = 28U;
constexpr float32_t RT_STARS_TASK_KERNEL_CREDIT_SCALE = 4294.9F;   // 2^32 / 1000M * 1000(ms)
constexpr uint8_t RT_STARS_TASK_KERNEL_CREDIT_SCALE_UINT8 = 4U;
constexpr uint16_t RT_STARS_DEFAULT_HCCL_FFTSPLUS_TIMEOUT = 1770U;
extern bool g_isAddrFlatDevice;
#define RT_STARS_DEFAULT_AICPU_KERNEL_CREDIT (!g_isAddrFlatDevice ? RT_STARS_DEFAULT_AICPU_KERNEL_CREDIT_MIN : RT_STARS_DEFAULT_AICPU_KERNEL_CREDIT_MAX)
/* stars send interrupt direction */
enum RtStarsSqeIntDirType {
    RT_STARS_SQE_INT_DIR_NO           = 0, // send no interrupt
    RT_STARS_SQE_INT_DIR_TO_TSCPU     = 1, // to tscpu
    RT_STARS_SQE_INT_DIR_TO_CTRLCPU   = 2, // to ctrlcpu
    RT_STARS_SQE_INT_DIR_TO_HOST      = 3, // to host
    RT_STARS_SQE_INT_DIR_END          = 4
};

enum RtStarsWriteValueSizeType {
    RT_STARS_WRITE_VALUE_SIZE_TYPE_8BIT   = 0,
    RT_STARS_WRITE_VALUE_SIZE_TYPE_16BIT  = 1,
    RT_STARS_WRITE_VALUE_SIZE_TYPE_32BIT  = 2,
    RT_STARS_WRITE_VALUE_SIZE_TYPE_64BIT  = 3,
    RT_STARS_WRITE_VALUE_SIZE_TYPE_128BIT = 4,
    RT_STARS_WRITE_VALUE_SIZE_TYPE_256BIT = 5
};

enum RtStarsMemcpyAsyncDataType {
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_INT8   = 0x00,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_INT16  = 0x10,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_INT32  = 0x20,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_UINT8  = 0x30,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_UINT16 = 0x40,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_UINT32 = 0x50,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_FP16   = 0x60,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_FP32   = 0x70,
    RT_STARS_MEMCPY_ASYNC_DATA_TYPE_BFP16  = 0x80,
    RT_STARS_MEMCPY_ASYNC_OP_RESERVED      = 0xF0
};

enum RtStarsMemcpyAsyncOperationKind {
    RT_STARS_MEMCPY_ASYNC_OP_KIND_CPY      = 0x00,
    RT_STARS_MEMCPY_ASYNC_OP_KIND_ADD      = 0x01,
    RT_STARS_MEMCPY_ASYNC_OP_KIND_MAX      = 0x02,
    RT_STARS_MEMCPY_ASYNC_OP_KIND_MIN      = 0x03,
    RT_STARS_MEMCPY_ASYNC_OP_KIND_EQUAL    = 0x04
};

// 1910b tiny conds op sub type
enum RtCondsSubType {
    CONDS_SUB_TYPE_MODEL_EXEC = 1,
    CONDS_SUB_TYPE_RDMA_1 = 2,
    CONDS_SUB_TYPE_RDMA_2 = 3,
    CONDS_SUB_TYPE_STREAM_SWITCH = 4,
    CONDS_SUB_TYPE_STREAM_SWITCH_EX = 5,
    CONDS_SUB_TYPE_STREAM_ACTIVE = 6,
    CONDS_SUB_TYPE_LABEL_SWITCH_BY_INDEX = 7,
    CONDS_SUB_TYPE_GET_FLOAT_STATUS = 8,
    CONDS_SUB_TYPE_MEM_WAIT_VALUE = 9,
    CONDS_SUB_TYPE_PI_VALUE_MODIFY = 10,
    CONDS_SUB_TYPE_DQS_ENQUEUE = 11,
    CONDS_SUB_TYPE_DQS_DEQUEUE = 12,
    CONDS_SUB_TYPE_DQS_PREPARE = 13,
    CONDS_SUB_TYPE_DQS_ZERO_COPY = 14,
    CONDS_SUB_TYPE_DQS_SCHED_END = 15,
    CONDS_SUB_TYPE_DQS_MBUF_FREE = 16,
    CONDS_SUB_TYPE_DQS_INTER_CHIP_PREPROC = 17,
    CONDS_SUB_TYPE_DQS_INTER_CHIP_POSTPROC = 18,
    CONDS_SUB_TYPE_DQS_ADSPC = 19,
    CONDS_SUB_TYPE_DQS_BATCH_DEQUEUE = 20,
    CONDS_SUB_TYPE_DQS_CONDITION_COPY = 21,
    CONDS_SUB_TYPE_DQS_FRAME_ALIGN = 22,
    CONDS_SUB_TYPE_MAX = 22,
};

enum RtStarsWriteValueSubType {
    RT_STARS_WRITE_VALUE_SUB_TYPE_DEFAULT = 0,
    RT_STARS_WRITE_VALUE_SUB_TYPE_EVENT_RESET = 1,
    RT_STARS_WRITE_VALUE_SUB_TYPE_RDMA_DB_SEND = 2,
    RT_STARS_WRITE_VALUE_SUB_TYPE_NOTIFY_RECORD_IPC_NO_PCIE = 3,
    RT_STARS_WRITE_VALUE_SUB_TYPE_NOTIFY_RECORD_IPC_PCIE = 4,
    RT_STARS_WRITE_VALUE_SUB_TYPE_MAX,
};

enum RtTopicType {
    TOPIC_TYPE_DEVICE_AICPU_ONLY = 0,
    TOPIC_TYPE_DEVICE_AICPU_FIRST = 1,
    TOPIC_TYPE_HOST_AICPU_ONLY = 2,
    TOPIC_TYPE_HOST_AICPU_FIRST = 3,
    TOPIC_TYPE_HOST_CTRL_CPU = 4,
    TOPIC_TYPE_DATA_CPU = 5,
    TOPIC_TYPE_DEVICE_CTRL_CPU = 6,
    TOPIC_TYPE_TS_CPU = 7,
    TOPIC_TYPE_DVPP_CPU = 8,
    TOPIC_TYPE_DEVICE_HOST_CTRL_CPU = 9,
    TOPIC_TYPE_DEVICE_AICPU_SRC_PID = 10,
};

enum RtModelExecutorFlag {
    MODEL_EXECUTOR_TS = 1,
    MODEL_EXECUTOR_AICPU = 2,
    MODEL_EXECUTOR_RESERVED = 3,
};

}  // namespace runtime
}  // namespace cce
#endif  // __CCE_RUNTIME_STARS_BASE_HPP__